# Generated by Django 5.2.8 on 2025-11-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket'), ('Paypal', 'Paypal')], max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('course_name', models.CharField(blank=True, max_length=250, null=True)),
                ('course_slug', models.SlugField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
